### ISSUE TITLE
Add to README: what is the difference from integrated i3-save-tree

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jdholtz/i3-restore#10]
### Description

I am not an expert in i3, but I found this page - looks like about the same session saving and restoring https://i3wm.org/docs/layout-saving.html

### To Reproduce

Read the README

### Expected Behavior

See the difference of integrated session restoring.

**Comment by jdholtz** [comment]
i3-save-tree only saves the window layouts of one or more workspaces. [This](https://i3wm.org/docs/layout-saving-1.png) is what the layout looks like when it is restored.

There are multiple indications in the Readme that show that i3-restore does much more, in that it can save and restore programs running in windows, not just the window layout.

> The script can correctly restore terminal subprocesses (such as Vim and ssh) and web browser instances exactly how they were before.

> Automatic saving and restoring of all i3 window layouts and programs running in your current i3 session

Is there more details that you would want to see in the Readme? What would those details be?

**Comment by jdholtz** [comment]
Hey @vitaly-zdanevich, do you have any follow-up to my comment above or can this issue be closed?
