### ISSUE TITLE
README: please add about kitty terminal sessions

### ISSUE THREAD

**Issue by vitaly-zdanevich** [jdholtz/i3-restore#14]
### Description

https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

I think this is good to have such information in the README - so people can grep and better understand before installing.

**Comment by jdholtz** [comment]
I haven't looked into startup sessions in Kitty (but I will). What do you think should be added about it?

**Comment by vitaly-zdanevich** [comment]
In README will be good to have a link to a ticket about this new feature (maybe this ticket), so people will understand better the current state of the project, using Ctrl-F "kitty". Even if something is not implemented - better to write about it. I will do a PR now, for the README.

**Comment by vitaly-zdanevich** [comment]
Created https://github.com/jdholtz/i3-restore/pull/15

**Comment by jdholtz** [comment]
Restoring Kitty sessions was implemented as a plugin in #24.
